### ISSUE TITLE
QRCODE PLUGIN integration

### ISSUE THREAD

**Issue by joshp23** [Flynntes/Sleeky#2]
I'm having fun hacking at your code here, and I was hoping you might be able to help me get a qr code image on the result page using this plugin

http://techlister.com/plugins-2/qrcode-plugin-for-yourls/354/

**Comment by joshp23** [comment]
I was able to make that plugin work by adding the following to index.php at line 65

> <center><img src="<?php if ( isset ( $return['qrimage']))
						        echo $return['qrcimg'];  ?>" alt="QRCode"></center>
it would be nice to see this added into the general config and theme. it's a pretty simple and nice plugin, and looks nice with your work as well.

**Comment by cjsmns** [comment]
I know this is about 5 years late, but might help someone out. I've just added the QR Code to be shown when you create a new short url. Since most QR Code plugins append `.qr` after the short link, I worked based on that. On my index.php page around line 95 where is shows your the stats link for your new short url, I basically duplicated that line, and changed the `+` to `.qr` to show the QR Code link, and then an `<img>` tag to show the code. My code below. It's not prettiest result, but it'll do me for my needs.

```
<span class="info">View info &amp; stats at <a href="<?php echo $shorturl; ?>+"><?php echo $url; ?>+</a></span><br />
<span class="info">View QR Code <a href="<?php echo $shorturl; ?>.qr"><?php echo $url; ?>.qr</a></span><br />
<img src="<?php echo $shorturl; ?>.qr">
```
